(source marmalade)
(source melpa)

(depends-on "cask")
(depends-on "dash")
(depends-on "epl")
(depends-on "evil")
(depends-on "evil-leader")
(depends-on "magit")
(depends-on "f")
(depends-on "goto-last-change")
(depends-on "nyan-mode")
(depends-on "pallet")
(depends-on "rainbow-delimiters")
(depends-on "s")
(depends-on "undo-tree")