(add-to-list 'load-path "~/.emacs.d/lisp")

(require 'packages)
(require 'appearance)
(require 'autocompletion)
(require 'editor)
(require 'shell)
(require 'mail)
(require 'www)
(require 'enhancements)
(require 'customizations)
(require 'hooks)
(require 'custom-org)
(require 'lisps)
(require 'clojure)
(require 'clisp)
(require 'python-dev)
(require 'js)
(require 'pgsql)
(require 'html)
(require 'documentation)
(require 'social)
(require 'music)
(require 'start)
